# Bundles a curated slice of the shared Hong Kong dim sum catalog into the app.
#
# The catalog itself lives in the instructions repository and holds native-resolution
# lossless PNGs (~2.3 MB each). Those are the right thing to attach to a GitHub
# Release, and the wrong thing to put 20 of inside a desktop installer: the app draws
# the dish at 56 CSS pixels. This writes 256x256 derivatives — still crisp at 200%
# display scale — plus a generated catalog module naming every dish in both languages.
#
# The output is COMMITTED, so a build never needs the (private) catalog repository and
# never fetches a food photo from anywhere. Re-run this when the catalog grows.
#
#   pwsh -File tools/sync-dimsum.ps1 [-CatalogRoot <path>] [-Count 20] [-Size 256]
#
# This handles the PHOTOS. The NAMES of every catalog dish — which release code names
# index, and which cost about 200 bytes each rather than 2.3 MB — are bundled by
# tools/sync-dimsum-roster.mjs. Run both when the catalog grows; the roster reads the
# manifest this writes to work out which dishes it can offer a photo for.

[CmdletBinding()]
param(
  [string]$CatalogRoot,
  [int]$Count = 20,
  [int]$Size = 256
)

$ErrorActionPreference = 'Stop'
Add-Type -AssemblyName System.Drawing

$repoRoot = Split-Path -Parent $PSScriptRoot

if (-not $CatalogRoot) {
  # Resolve the instructions repository from the user's Documents folder rather than
  # hard-coding a drive or a username.
  $documents = [Environment]::GetFolderPath('MyDocuments')
  $CatalogRoot = Join-Path $documents 'GitHub\agent-global-memory\dim-sum'
}

$indexPath = Join-Path $CatalogRoot 'index.json'
if (-not (Test-Path $indexPath)) {
  Write-Error "Dim sum catalog not found at $indexPath. Clone the instructions repository, or pass -CatalogRoot."
}

$index = Get-Content -LiteralPath $indexPath -Raw -Encoding UTF8 | ConvertFrom-Json
Write-Host "Catalog: $($index.total) records, status $($index.catalogStatus)"

# Only records whose PNG actually exists on disk are eligible. A dish whose image has
# not been generated yet would render as a broken picture, which is worse than a
# smaller selection.
$available = @()
foreach ($dish in $index.dishes) {
  $img = Join-Path $CatalogRoot $dish.image.path
  if (Test-Path $img) { $available += [pscustomobject]@{ dish = $dish; source = $img } }
}
Write-Host "$($available.Count) records have a bundled image."
if ($available.Count -eq 0) { Write-Error 'No catalog images are available yet.' }

# Spread the selection across the catalog so the surprise is not twenty variations of
# the same dumpling.
$take = [Math]::Min($Count, $available.Count)
$step = [Math]::Max(1, [Math]::Floor($available.Count / $take))
$selected = @()
for ($i = 0; $i -lt $available.Count -and $selected.Count -lt $take; $i += $step) {
  $selected += $available[$i]
}

$outDir = Join-Path $repoRoot 'app\dimsum'
New-Item -ItemType Directory -Force -Path $outDir | Out-Null
Get-ChildItem -LiteralPath $outDir -Filter '*.png' -ErrorAction SilentlyContinue | Remove-Item -Force

$records = @()
foreach ($entry in $selected) {
  $dish = $entry.dish
  $destName = "$($dish.slug).png"
  $dest = Join-Path $outDir $destName

  $src = [System.Drawing.Image]::FromFile($entry.source)
  try {
    $bmp = New-Object System.Drawing.Bitmap($Size, $Size)
    try {
      $gfx = [System.Drawing.Graphics]::FromImage($bmp)
      try {
        $gfx.InterpolationMode = [System.Drawing.Drawing2D.InterpolationMode]::HighQualityBicubic
        $gfx.PixelOffsetMode = [System.Drawing.Drawing2D.PixelOffsetMode]::HighQuality
        $gfx.SmoothingMode = [System.Drawing.Drawing2D.SmoothingMode]::HighQuality
        $gfx.DrawImage($src, 0, 0, $Size, $Size)
      } finally { $gfx.Dispose() }
      $bmp.Save($dest, [System.Drawing.Imaging.ImageFormat]::Png)
    } finally { $bmp.Dispose() }
  } finally { $src.Dispose() }

  $records += [pscustomobject]@{
    id      = $dish.id
    slug    = $dish.slug
    en      = $dish.name.en
    yue     = $dish.name.zhHant
    jyutping = $dish.jyutping
    image   = "dimsum/$destName"
    altEn   = $dish.image.alt.en
    altYue  = $dish.image.alt.yue
    source  = $dish.image.path
  }
  Write-Host "  + $($dish.name.en) -> $destName"
}

# The generated module is plain browser JS in the same shape as the rest of app/.
$sb = [System.Text.StringBuilder]::new()
[void]$sb.AppendLine('/* GENERATED by tools/sync-dimsum.ps1 — do not edit by hand.')
[void]$sb.AppendLine('   A curated slice of the shared Hong Kong dim sum catalog, bundled as local')
[void]$sb.AppendLine('   assets. Names are the catalog''s own and stay factual at every funny level;')
[void]$sb.AppendLine('   humour styles the copy around a dish, never the dish. */')
[void]$sb.AppendLine('(function (g) {')
[void]$sb.AppendLine('  "use strict";')
[void]$sb.AppendLine('')
[void]$sb.AppendLine("  var CATALOG_STATUS = " + ($index.catalogStatus | ConvertTo-Json) + ";")
[void]$sb.AppendLine('')
[void]$sb.AppendLine('  var DISHES = [')
$lines = @()
foreach ($r in $records) {
  $lines += '    { id: ' + ($r.id | ConvertTo-Json) +
            ', slug: ' + ($r.slug | ConvertTo-Json) +
            ', en: ' + ($r.en | ConvertTo-Json) +
            ', yue: ' + ($r.yue | ConvertTo-Json) +
            ', jyutping: ' + ($r.jyutping | ConvertTo-Json) +
            ', image: ' + ($r.image | ConvertTo-Json) +
            ', source: ' + ($r.source | ConvertTo-Json) +
            ', alt: { en: ' + ($r.altEn | ConvertTo-Json) + ', yue: ' + ($r.altYue | ConvertTo-Json) + ' } }'
}
[void]$sb.AppendLine(($lines -join ",`n"))
[void]$sb.AppendLine('  ];')
[void]$sb.AppendLine('')
[void]$sb.AppendLine('  g.CX_DIMSUM = {')
[void]$sb.AppendLine('    VERSION: 2,')
[void]$sb.AppendLine('    CATALOG_STATUS: CATALOG_STATUS,')
[void]$sb.AppendLine('    DISHES: DISHES,')
[void]$sb.AppendLine('')
[void]$sb.AppendLine('    /** One fresh draw per call. `rate` is the probability of showing anything at')
[void]$sb.AppendLine('     *  all — the caller passes 0.01 at launch and 1 only for the settings preview. */')
[void]$sb.AppendLine('    draw: function (rate, rng) {')
[void]$sb.AppendLine('      var r = typeof rate === "number" ? rate : 0.01;')
[void]$sb.AppendLine('      var random = rng || Math.random;')
[void]$sb.AppendLine('      if (!DISHES.length) return null;')
[void]$sb.AppendLine('      if (random() >= r) return null;')
[void]$sb.AppendLine('      return DISHES[Math.floor(random() * DISHES.length) % DISHES.length];')
[void]$sb.AppendLine('    },')
[void]$sb.AppendLine('')
[void]$sb.AppendLine('    byId: function (id) {')
[void]$sb.AppendLine('      for (var i = 0; i < DISHES.length; i++) if (DISHES[i].id === id) return DISHES[i];')
[void]$sb.AppendLine('      return null;')
[void]$sb.AppendLine('    },')
[void]$sb.AppendLine('')
[void]$sb.AppendLine('    bySlug: function (slug) {')
[void]$sb.AppendLine('      for (var i = 0; i < DISHES.length; i++) if (DISHES[i].slug === slug) return DISHES[i];')
[void]$sb.AppendLine('      return null;')
[void]$sb.AppendLine('    }')
[void]$sb.AppendLine('  };')
[void]$sb.AppendLine('})(window);')

$modulePath = Join-Path $repoRoot 'app\cx-dimsum.js'
[System.IO.File]::WriteAllText($modulePath, $sb.ToString(), (New-Object System.Text.UTF8Encoding($false)))

# A machine-readable copy for the release tooling, which needs the full-resolution
# source path to attach the real photo to a GitHub Release.
$manifest = [pscustomobject]@{
  # Deliberately not $CatalogRoot: that path runs through the operator's home
  # directory, and this manifest is committed and published.
  generatedFrom  = 'the shared Hong Kong dim sum catalog'
  catalogStatus  = $index.catalogStatus
  catalogTotal   = $index.total
  bundledSize    = $Size
  dishes         = $records
} | ConvertTo-Json -Depth 6
[System.IO.File]::WriteAllText((Join-Path $repoRoot 'app\dimsum\manifest.json'), $manifest, (New-Object System.Text.UTF8Encoding($false)))

Write-Host ""
Write-Host "Bundled $($records.Count) dishes at ${Size}x${Size} into app/dimsum/"
Write-Host "Wrote app/cx-dimsum.js and app/dimsum/manifest.json"
